name: Release DevOps with Docker # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main

# Job called build runs-on ubuntu-latest
jobs:
  build:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v4

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dartherm/simple-express:latest
      # Render Deploy
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_deployment: true
          clear_cache: true
          wait_deploy: true
